Update prettier.yml

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -20,14 +20,9 @@ jobs:
         with:
           cache: npm
           node-version: lts/*
-      - run: npm ci --ignore-scripts --only-dev
-      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
-        with:
-          path: node_modules/.cache/prettier/.prettier-cache
-          key: prettier-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.gitignore') }}
       - name: check if workflows needs prettier
-        run: npx prettier --cache --check ".github/workflows/**/*.yml" || (echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1)
-      - run: npx prettier --ignore-path .gitignore --cache --write .
+        run: npx -y prettier --cache --check ".github/workflows/**/*.yml" || (echo "An action can't make changes to actions, you'll have to run prettier manually" && exit 1)
+      - run: npx -y prettier --ignore-path .gitignore --cache --write .
       - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # v9
         with:
           default_author: github_actions
